<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>job-portfolio (1).ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="RemoteFramework.EF31" Version="0.3.1" />
    <PackageReference Include="SimpleModal.WPF" Version="1.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Images\Images.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Images.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\ActivitiesView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ConfigView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\InteresseView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\QualificationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\FormationView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\ProjektView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Images\Images.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Images.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\ActivitiesView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Views\ConfigView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Views\InteresseView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Views\QualificationView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Views\FormationView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Views\ProjektView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
